# -*- coding: utf-8 -*-
"""covid19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IP2w7xFV45ZQ2dZhWbwPHbPNEeFwWBAL
"""

bins=[0,19,89,198,1000]
labels=["Low","Moderate","High","Critical"]
df["CFR_Category"]=pd.cut(df["CFR(%)"],bins=bins,labels=labels)
print(df)

from google.colab import files
uploaded = files.upload()

import pandas as pd
df=pd.read_csv("covid_19_clean_complete.csv")
print(df)

import pandas as pd
df=pd.read_csv("covid_19_clean_complete.csv")
print(df.columns)

df["CFR(%)"]=(df["Deaths"]/df["Confirmed"])*100
print(df)
print(df.head)

df_no_nan=df[df.notnull().all(axis=1)]
print(df_no_nan)

df["Recovery_Rate(%)"]=(df["Recovered"]/df["Confirmed"])*100
print(df)
print(df.head)

df_no_nan=df[df.notnull().all(axis=1)]
print(df_no_nan)

df["Active_Cases"]=df["Confirmed"]-df["Deaths"]+df["Recovered"]
print(df)
print(df.head)

df['Cases_per_100k']=(df['Confirmed']/df['Confirmed']+df['Deaths']+df['Recovered'])*100000
print(df)
print(df.head)

df_no_nan=df[df.notnull().all(axis=1)]
print(df_no_nan)

import numpy as np
df["Log_Confirmed_Cases"]=np.log1p(df["Confirmed"])
print(df)

df["Risk_Score"]=(df["CFR(%)"]*0.7)+(df["Cases_per_100k"]*0.3)
print(df)

df_no_nan=df[df.notnull().all(axis=1)]
print(df_no_nan)

